[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["src/**"]

[deploy]
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
