create table articles (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  title text check (char_length(title) > 3),
  summary text check (char_length(summary) > 3),
  body text check (char_length(body) > 3),
  image_src text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table articles enable row level security;

create policy "Individuals can create articles." on articles for
    insert with check (auth.uid() = user_id);

create policy "Anyone can view articles. " on articles for
    select using (true);

create policy "Individuals can update their own articles." on articles for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own articles." on articles for
    delete using (auth.uid() = user_id);
